apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: output
  namespace: sn-labs-ayoubchaieb7
spec:
  finally:
    - name: deploy
      params:
        - name: SCRIPT
          value: oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
      taskRef:
        kind: ClusterTask
        name: openshift-client
  params:
    - default: 'image-registry.openshift-image-registry.svc:5000/sn-labs-ayoubchaieb7/tekton-lab:latest'
      name: build-image
      type: string
    - default: cicd-app
      name: app-name
      type: string
  tasks:
    - name: cleanup
      taskRef:
        kind: Task
        name: cleanup
      workspaces:
        - name: source
          workspace: output
    - name: nose
      params:
        - name: args
          value: '-v --with-spec --spec-color'
      runAfter:
        - flake8
      taskRef:
        kind: Task
        name: nose
      workspaces:
        - name: source
          workspace: output
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.build-image)
      runAfter:
        - nose
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: output
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/ayoub-chaieb/ci-cd-final-project.git'
      runAfter:
        - cleanup
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: output
    - name: flake8
      params:
        - name: image
          value: 'python:3.9-slim'
        - name: path
          value: .
        - name: requirements_file
          value: requirements.txt
        - name: args
          value:
            - '--count'
            - '--max-complexity=10'
            - '--max-line-length=127'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: flake8
      workspaces:
        - name: source
          workspace: output
  workspaces:
    - name: output