apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{},"name":"nose","namespace":"sn-labs-ayoubchaieb7"},"spec":{"description":"This task will run nose test.","params":[{"default":"-v","description":"Arguments to pass to nose","name":"args","type":"string"}],"steps":[{"image":"python:3.9-slim","name":"nosetests","script":"#!/bin/bash\nset -e\npython -m pip install --upgrade pip wheel\npip install -r requirements.txt\nnosetests $(params.args)\n","workingDir":"$(workspaces.source.path)"}],"workspaces":[{"name":"source"}]}}
  creationTimestamp: '2025-12-12T14:40:17Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          .: {}
          'f:description': {}
          'f:params': {}
          'f:steps': {}
          'f:workspaces': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2025-12-12T14:40:17Z'
  name: nose
  namespace: sn-labs-ayoubchaieb7
  resourceVersion: '2532720770'
  uid: 80ed9d5d-a1d3-4bb6-aaf6-5629fe24f20d
spec:
  description: This task will run nose test.
  params:
    - default: '-v'
      description: Arguments to pass to nose
      name: args
      type: string
  steps:
    - computeResources: {}
      image: 'python:3.9-slim'
      name: nosetests
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
