apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  creationTimestamp: '2025-12-12T15:42:08Z'
  generation: 1
  managedFields:
    - apiVersion: triggers.tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
      manager: Mozilla
      operation: Update
      time: '2025-12-12T15:42:08Z'
  name: cd-binding
  namespace: sn-labs-ayoubchaieb7
  resourceVersion: '2532801046'
  uid: ada81ae4-a641-4b61-af49-bc704c642053
spec:
  params:
    - name: repository
      value: $(body.repository.url)
    - name: branch
      value: $(body.ref)
