apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cd-template
  namespace: sn-labs-ayoubchaieb7
spec:
  params:
    - default: ' '
      description: The git repo
      name: repository
    - default: master
      description: the branch for the git repo
      name: branch
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cd-pipeline-run-
      spec:
        params:
          - name: repo-url
            value: $(tt.params.repository)
          - name: branch
            value: $(tt.params.branch)
        pipelineRef:
          name: output
        serviceAccountName: pipeline
        workspaces:
          - name: output
            persistentVolumeClaim:
              claimName: pipelinerun-pvc
